### ISSUE TITLE
"rpmScriptType: parameter not set" after adding *debian* postinst script

### ISSUE THREAD

**Issue by ringods** [raphaelcohn/swaddle#29]
After adding a postinst script snippet to my debian package, I get this error:

```
/usr/bin/swaddle: 25064: /usr/bin/swaddle: rpmScriptType: parameter not set
```

I suspect there is still some copy-paste that crept into `deb.functions` from the `rpm.functions`:

https://github.com/raphaelcohn/swaddle/blob/8945848b7c5530921007ff2a5d792ad264b53c6e/lib/shellfire/swaddle/build/package/deb.functions#L254

https://github.com/raphaelcohn/swaddle/blob/8945848b7c5530921007ff2a5d792ad264b53c6e/lib/shellfire/swaddle/build/package/rpm.functions#L460

**Comment by raphaelcohn** [comment]
OK. This is the weakest part of the current codebase - the least well tested (there's lots of paths through it) and the least run, too. I'll look at this now.

**Comment by raphaelcohn** [comment]
Commit 16eebfb should fix this. I'll do a release now.

**Comment by raphaelcohn** [comment]
I've made a [release](https://github.com/raphaelcohn/swaddle/releases/tag/release_2015.0504.0802-1) - let me know how it goes. I'll start work now on disabling repository publication latter this morning.

**Comment by ringods** [comment]
will try this evening.

Regarding publishing of the repository: from a user perspective, it would be consistent that an action would only be taken when the corresponding folder + conf file would exist:
* need a debian package: create the `deb` folder and conf file.
* need a apt repo: create the `apt` folder and conf file (even empty)

**Comment by raphaelcohn** [comment]
Point 1: (need a debian package) - that's how things currently happen (see `swaddling/swaddle` for how this works for swaddle itself).
Point 2: there is no conf as such except that held in `swaddling.conf` (or snippets in `swaddling.conf.d`, so one could have `apt` repo details there). Swaddle is intended as release tooling, with a bias towards git and GitHub, and to make it as easy possible to deploy for the most common repo typos. With almost no configuration, it does this. With extra files, there's more to get wrong. I'm very reluctant to split package creation from repo creation and release; it's completely artificial and, frankly, erroneous for most controlled environments. swaddle's goal is to produce multi-package versioned releases. If not, then, it's just a slightly better fpm.

I'll chew the ideas over for the rest of today rather than cut code in haste.

**Comment by ringods** [comment]
@raphaelcohn finally got the time to test the release. No error anymore, but no `postinst` script either in the resulting package. :disappointed: 

```
root@d244e18c8d32:/pipeline/source/target/download/apt/pool/multiverse/r/rq-web-api-elx# ar x rq-web-api-elx_2015.0506.0806-2_amd64.deb
root@d244e18c8d32:/pipeline/source/target/download/apt/pool/multiverse/r/rq-web-api-elx# tar tfz control.tar.gz
./
./md5sums
./control
```

Debug log in [gist](https://gist.github.com/ringods/5aa082d147bf68b3e76b)

**Comment by raphaelcohn** [comment]
That's rather odd. I'm tied up with a client today - I'll try and take a look this evening.

**Comment by raphaelcohn** [comment]
The gist refuses to display raw - any chance you could tail -n 10000 or somesuch? Must be an internal GitHub limit.

**Comment by raphaelcohn** [comment]
Right, I've tracked this down in the gist you sent me offline. I've pushed `7d5b781f1815a438a2f6f63361d6c5608004ae2e`, which should fix this. In essence, the code was doing `return` when encountering a missing script folder, rather than a `continue`. Depending on local configuration would change whether scripts would be added or not.

**Comment by raphaelcohn** [comment]
[Release](https://github.com/raphaelcohn/swaddle/releases/tag/release_2015.0507.0828-1)

**Comment by ringods** [comment]
Release is working! :+1:
